### Extrayendo la Dirección de Compra

Tenemos los tickets de una tienda de electrónica. Primero, reciclaremos el código de la sesión anterior para encontrar los conjuntos frecuentes. Luego, inyectaremos el algoritmo de reglas de asociación para separar los antecedentes de los consecuentes.

In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

# 1. DATOS CRUDOS
tickets_tech = [
    ['Laptop', 'Funda', 'Ratón', 'Cable HDMI'],
    ['Laptop', 'Ratón', 'Monitor'],
    ['Ratón', 'Pilas', 'Teclado'],
    ['Laptop', 'Funda'],
    ['Ratón', 'Pilas'],
    ['Laptop', 'Funda', 'Ratón'],
    ['Monitor', 'Cable HDMI'],
    ['Laptop', 'Ratón']
]

# 2. TRANSFORMACIÓN (One-Hot)
te = TransactionEncoder()
matriz_bool = te.fit_transform(tickets_tech)
df_tech = pd.DataFrame(matriz_bool, columns=te.columns_)

# 3. CONJUNTOS FRECUENTES (La clase pasada)
itemsets = apriori(df_tech, min_support=0.3, use_colnames=True)

# 4. REGLAS DE ASOCIACIÓN (El tema de hoy)
# Usamos 'confidence' como métrica base para generar las direcciones
reglas = association_rules(itemsets, metric="confidence", min_threshold=0.5)

print("--- TODAS LAS REGLAS DESCUBIERTAS ---")
display(reglas[['antecedents', 'consequents', 'support', 'confidence', 'lift']])

--- TODAS LAS REGLAS DESCUBIERTAS ---

           antecedents          consequents  support  confidence      lift
0  frozenset({Laptop})   frozenset({Funda})    0.375    0.600000  1.600000
1   frozenset({Funda})  frozenset({Laptop})    0.375    1.000000  1.600000
2  frozenset({Laptop})   frozenset({Ratón})    0.500    0.800000  1.066667
3   frozenset({Ratón})  frozenset({Laptop})    0.500    0.666667  1.066667

### Reto Analítico: Laptop vs Ratón

Observa tu tabla resultante. El algoritmo creó dos reglas distintas para los mismos artículos:
1. `(Laptop) -> (Ratón)`
2. `(Ratón) -> (Laptop)`

Filtremos la tabla usando Pandas para ver exclusivamente estas dos reglas y comparar su Confianza.

In [2]:
# Convertimos los frozensets a strings temporales para poder filtrar fácilmente en Pandas
reglas['ant_str'] = reglas['antecedents'].apply(lambda x: ', '.join(list(x)))
reglas['con_str'] = reglas['consequents'].apply(lambda x: ', '.join(list(x)))

# Filtramos la batalla direccional
batalla_direccional = reglas[
    ((reglas['ant_str'] == 'Laptop') & (reglas['con_str'] == 'Ratón')) |
    ((reglas['ant_str'] == 'Ratón') & (reglas['con_str'] == 'Laptop'))
]

print("--- ANÁLISIS DIRECCIONAL (Laptop vs Ratón) ---")
display(batalla_direccional[['antecedents', 'consequents', 'confidence', 'lift']])

--- ANÁLISIS DIRECCIONAL (Laptop vs Ratón) ---

           antecedents          consequents  confidence      lift
2  frozenset({Laptop})   frozenset({Ratón})    0.800000  1.066667
3   frozenset({Ratón})  frozenset({Laptop})    0.666667  1.066667

### 🧠 Evaluación Ejecutiva (Responde aquí)

El gerente de la tienda quiere hacer una estrategia de "Venta Cruzada" (Cross-selling) en la zona de cajas registradoras. Tiene espacio físico limitado y te hace dos preguntas:

**1. Análisis de Confianza:**
Basado en los resultados de tu `batalla_direccional`, ¿qué estrategia matemática es correcta?
*   Opción A: Poner exhibidores de Ratones junto a las Laptops.
*   Opción B: Poner exhibidores de Laptops junto a los Ratones.
> **Justifica usando el porcentaje exacto de Confianza:** [Escribe tu justificación aquí]

**2. Análisis de Lift:**
Observa que el valor de *Lift* es exactamente el mismo para `Laptop -> Ratón` que para `Ratón -> Laptop`. ¿Por qué ocurre esto matemáticamente? (Pista: Revisa la fórmula del Lift de la sesión pasada).
> **Tu Respuesta:** [Escribe tu justificación matemática aquí]