In [1]:
from IPython.display import display, HTML

cubos_olap = """
<div style="font-family: Arial, sans-serif; max-width: 900px; margin: auto; color: #333;">
    <h2 style="text-align: center; color: #5B1A3A; margin-bottom: 30px;">Las 4 Operaciones Fundamentales del Cubo OLAP</h2>

    <!-- SVG Definitions (Flechas) -->
    <svg width="0" height="0">
        <defs>
            <marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
                <path d="M 0 0 L 10 5 L 0 10 z" fill="#5B1A3A" />
            </marker>
        </defs>
    </svg>

    <!-- 1. ROLL-UP -->
    <div style="background: white; border: 1px solid #ddd; border-radius: 8px; padding: 20px; margin-bottom: 25px; box-shadow: 0 4px 6px rgba(0,0,0,0.05);">
        <h3 style="color: #5B1A3A; margin-top: 0;">1. Roll-up (Subir / Resumir)</h3>
        <p style="font-size: 14px; color: #666; margin-bottom: 5px;">Disminuir el nivel de detalle. Pasar de ver "Ventas por Día" a "Ventas por Año".</p>
        <div style="background: #f8f9fa; border-left: 4px solid #5B1A3A; padding: 8px 12px; font-family: monospace; font-size: 14px; margin-bottom: 15px; color: #d63384;">
            En Pandas: df.groupby('Año').sum()
        </div>
        <div style="display: flex; align-items: center; justify-content: space-around; flex-wrap: wrap;">
            
            <!-- Cubo Base -->
            <svg width="250" height="210" viewBox="0 0 250 210">
                <polygon points="60,60 180,60 225,30 105,30" fill="#FFF8E7" stroke="#5B1A3A" stroke-width="1.2"/>
                <polygon points="180,60 225,30 225,130 180,160" fill="#FFF8E7" stroke="#5B1A3A" stroke-width="1.2"/>
                <rect x="60" y="60" width="120" height="100" fill="#FFF8E7" stroke="#5B1A3A" stroke-width="1.2"/>
                <line x1="100" y1="60" x2="100" y2="160" stroke="#5B1A3A"/><line x1="140" y1="60" x2="140" y2="160" stroke="#5B1A3A"/>
                <line x1="60" y1="85" x2="180" y2="85" stroke="#5B1A3A"/><line x1="60" y1="110" x2="180" y2="110" stroke="#5B1A3A"/><line x1="60" y1="135" x2="180" y2="135" stroke="#5B1A3A"/>
                <line x1="100" y1="60" x2="145" y2="30" stroke="#5B1A3A"/><line x1="140" y1="60" x2="185" y2="30" stroke="#5B1A3A"/>
                <line x1="75" y1="50" x2="195" y2="50" stroke="#5B1A3A"/><line x1="90" y1="40" x2="210" y2="40" stroke="#5B1A3A"/>
                <line x1="180" y1="85" x2="225" y2="55" stroke="#5B1A3A"/><line x1="180" y1="110" x2="225" y2="80" stroke="#5B1A3A"/><line x1="180" y1="135" x2="225" y2="105" stroke="#5B1A3A"/>
                <line x1="195" y1="50" x2="195" y2="150" stroke="#5B1A3A"/><line x1="210" y1="40" x2="210" y2="140" stroke="#5B1A3A"/>
                
                <line x1="45" y1="160" x2="45" y2="60" stroke="#5B1A3A" stroke-width="1.5" marker-end="url(#arrow)"/><text x="35" y="115" transform="rotate(-90, 35, 115)" text-anchor="middle" font-size="12" fill="#5B1A3A" font-weight="bold">Día</text>
                <line x1="60" y1="175" x2="180" y2="175" stroke="#5B1A3A" stroke-width="1.5" marker-end="url(#arrow)"/><text x="120" y="195" text-anchor="middle" font-size="12" fill="#5B1A3A" font-weight="bold">Producto</text>
            </svg>

            <div style="text-align: center; color: #5B1A3A; font-weight: bold;">
                <span style="font-size: 24px;">&#10230;</span><br>Roll-up
            </div>

            <!-- Cubo Roll-up (Año) -->
            <svg width="250" height="210" viewBox="0 0 250 210">
                <polygon points="60,135 180,135 225,105 105,105" fill="#FFF8E7" stroke="#5B1A3A" stroke-width="1.2"/>
                <polygon points="180,135 225,105 225,130 180,160" fill="#FFF8E7" stroke="#5B1A3A" stroke-width="1.2"/>
                <rect x="60" y="135" width="120" height="25" fill="#FFF8E7" stroke="#5B1A3A" stroke-width="1.2"/>
                <line x1="100" y1="135" x2="100" y2="160" stroke="#5B1A3A"/><line x1="140" y1="135" x2="140" y2="160" stroke="#5B1A3A"/>
                <line x1="100" y1="135" x2="145" y2="105" stroke="#5B1A3A"/><line x1="140" y1="135" x2="185" y2="105" stroke="#5B1A3A"/>
                <line x1="75" y1="125" x2="195" y2="125" stroke="#5B1A3A"/><line x1="90" y1="115" x2="210" y2="115" stroke="#5B1A3A"/>
                <line x1="195" y1="125" x2="195" y2="150" stroke="#5B1A3A"/><line x1="210" y1="115" x2="210" y2="140" stroke="#5B1A3A"/>
                
                <line x1="45" y1="160" x2="45" y2="135" stroke="#5B1A3A" stroke-width="1.5" marker-end="url(#arrow)"/><text x="35" y="150" transform="rotate(-90, 35, 150)" text-anchor="middle" font-size="12" fill="#5B1A3A" font-weight="bold">Año</text>
            </svg>
        </div>
    </div>

    <!-- 2. DRILL-DOWN -->
    <div style="background: white; border: 1px solid #ddd; border-radius: 8px; padding: 20px; margin-bottom: 25px; box-shadow: 0 4px 6px rgba(0,0,0,0.05);">
        <h3 style="color: #5B1A3A; margin-top: 0;">2. Drill-down (Bajar / Detallar)</h3>
        <p style="font-size: 14px; color: #666; margin-bottom: 5px;">Aumentar el nivel de detalle. Pasar de ver "Ventas por País" a "Ventas por País y Ciudad".</p>
        <div style="background: #f8f9fa; border-left: 4px solid #5B1A3A; padding: 8px 12px; font-family: monospace; font-size: 14px; margin-bottom: 15px; color: #d63384;">
            En Pandas: df.groupby(['País', 'Ciudad']).sum()
        </div>
        <div style="display: flex; align-items: center; justify-content: space-around; flex-wrap: wrap;">
            
            <!-- Cubo Drill-down Left (País) -->
            <svg width="250" height="210" viewBox="0 0 250 210">
                <polygon points="60,60 180,60 195,50 75,50" fill="#FFF8E7" stroke="#5B1A3A" stroke-width="1.2"/>
                <polygon points="180,60 195,50 195,150 180,160" fill="#FFF8E7" stroke="#5B1A3A" stroke-width="1.2"/>
                <rect x="60" y="60" width="120" height="100" fill="#FFF8E7" stroke="#5B1A3A" stroke-width="1.2"/>
                <line x1="100" y1="60" x2="100" y2="160" stroke="#5B1A3A"/><line x1="140" y1="60" x2="140" y2="160" stroke="#5B1A3A"/>
                <line x1="60" y1="85" x2="180" y2="85" stroke="#5B1A3A"/><line x1="60" y1="110" x2="180" y2="110" stroke="#5B1A3A"/><line x1="60" y1="135" x2="180" y2="135" stroke="#5B1A3A"/>
                <line x1="100" y1="60" x2="115" y2="50" stroke="#5B1A3A"/><line x1="140" y1="60" x2="155" y2="50" stroke="#5B1A3A"/>
                <line x1="180" y1="85" x2="195" y2="75" stroke="#5B1A3A"/><line x1="180" y1="110" x2="195" y2="100" stroke="#5B1A3A"/><line x1="180" y1="135" x2="195" y2="125" stroke="#5B1A3A"/>
                
                <line x1="50" y1="50" x2="65" y2="40" stroke="#5B1A3A" stroke-width="1.5" marker-end="url(#arrow)"/><text x="70" y="30" transform="rotate(-33.6, 70, 30)" font-size="12" fill="#5B1A3A" font-weight="bold">País</text>
            </svg>

            <div style="text-align: center; color: #5B1A3A; font-weight: bold;">
                <span style="font-size: 24px;">&#10230;</span><br>Drill-down
            </div>

            <!-- Cubo Base Expandido (País y Ciudad) -->
            <svg width="250" height="210" viewBox="0 0 250 210">
                <polygon points="60,60 180,60 225,30 105,30" fill="#FFF8E7" stroke="#5B1A3A" stroke-width="1.2"/>
                <polygon points="180,60 225,30 225,130 180,160" fill="#FFF8E7" stroke="#5B1A3A" stroke-width="1.2"/>
                <rect x="60" y="60" width="120" height="100" fill="#FFF8E7" stroke="#5B1A3A" stroke-width="1.2"/>
                <line x1="100" y1="60" x2="100" y2="160" stroke="#5B1A3A"/><line x1="140" y1="60" x2="140" y2="160" stroke="#5B1A3A"/>
                <line x1="60" y1="85" x2="180" y2="85" stroke="#5B1A3A"/><line x1="60" y1="110" x2="180" y2="110" stroke="#5B1A3A"/><line x1="60" y1="135" x2="180" y2="135" stroke="#5B1A3A"/>
                <line x1="100" y1="60" x2="145" y2="30" stroke="#5B1A3A"/><line x1="140" y1="60" x2="185" y2="30" stroke="#5B1A3A"/>
                <line x1="75" y1="50" x2="195" y2="50" stroke="#5B1A3A"/><line x1="90" y1="40" x2="210" y2="40" stroke="#5B1A3A"/>
                <line x1="180" y1="85" x2="225" y2="55" stroke="#5B1A3A"/><line x1="180" y1="110" x2="225" y2="80" stroke="#5B1A3A"/><line x1="180" y1="135" x2="225" y2="105" stroke="#5B1A3A"/>
                <line x1="195" y1="50" x2="195" y2="150" stroke="#5B1A3A"/><line x1="210" y1="40" x2="210" y2="140" stroke="#5B1A3A"/>
                
                <line x1="50" y1="50" x2="95" y2="20" stroke="#5B1A3A" stroke-width="1.5" marker-end="url(#arrow)"/><text x="65" y="25" transform="rotate(-33.6, 65, 25)" font-size="12" fill="#5B1A3A" font-weight="bold">País y Ciudad</text>
            </svg>
        </div>
    </div>

    <!-- 3. SLICE -->
    <div style="background: white; border: 1px solid #ddd; border-radius: 8px; padding: 20px; margin-bottom: 25px; box-shadow: 0 4px 6px rgba(0,0,0,0.05);">
        <h3 style="color: #5B1A3A; margin-top: 0;">3. Slice (Rebanar)</h3>
        <p style="font-size: 14px; color: #666; margin-bottom: 5px;">Filtrar el cubo utilizando una sola dimensión (como cortar una rebanada de pastel).</p>
        <div style="background: #f8f9fa; border-left: 4px solid #5B1A3A; padding: 8px 12px; font-family: monospace; font-size: 14px; margin-bottom: 15px; color: #d63384;">
            En Pandas: df[df['Ciudad'] == 'Tijuana']
        </div>
        <div style="display: flex; align-items: center; justify-content: space-around; flex-wrap: wrap;">
            
            <svg width="250" height="210" viewBox="0 0 250 210">
                <polygon points="60,60 180,60 225,30 105,30" fill="#FFF8E7" stroke="#5B1A3A" stroke-width="1.2"/>
                <polygon points="180,60 225,30 225,130 180,160" fill="#FFF8E7" stroke="#5B1A3A" stroke-width="1.2"/>
                <rect x="60" y="60" width="120" height="100" fill="#FFF8E7" stroke="#5B1A3A" stroke-width="1.2"/>
                <line x1="100" y1="60" x2="100" y2="160" stroke="#5B1A3A"/><line x1="140" y1="60" x2="140" y2="160" stroke="#5B1A3A"/>
                <line x1="60" y1="85" x2="180" y2="85" stroke="#5B1A3A"/><line x1="60" y1="110" x2="180" y2="110" stroke="#5B1A3A"/><line x1="60" y1="135" x2="180" y2="135" stroke="#5B1A3A"/>
                <line x1="100" y1="60" x2="145" y2="30" stroke="#5B1A3A"/><line x1="140" y1="60" x2="185" y2="30" stroke="#5B1A3A"/>
                <line x1="75" y1="50" x2="195" y2="50" stroke="#5B1A3A"/><line x1="90" y1="40" x2="210" y2="40" stroke="#5B1A3A"/>
                <line x1="180" y1="85" x2="225" y2="55" stroke="#5B1A3A"/><line x1="180" y1="110" x2="225" y2="80" stroke="#5B1A3A"/><line x1="180" y1="135" x2="225" y2="105" stroke="#5B1A3A"/>
                <line x1="195" y1="50" x2="195" y2="150" stroke="#5B1A3A"/><line x1="210" y1="40" x2="210" y2="140" stroke="#5B1A3A"/>
            </svg>

            <div style="text-align: center; color: #5B1A3A; font-weight: bold;">
                <span style="font-size: 24px;">&#10230;</span><br>Slice
            </div>

            <svg width="250" height="210" viewBox="0 0 250 210">
                <rect x="60" y="60" width="120" height="100" fill="#E6D3DC" stroke="#5B1A3A" stroke-width="2"/>
                <line x1="100" y1="60" x2="100" y2="160" stroke="#5B1A3A"/><line x1="140" y1="60" x2="140" y2="160" stroke="#5B1A3A"/>
                <line x1="60" y1="85" x2="180" y2="85" stroke="#5B1A3A"/><line x1="60" y1="110" x2="180" y2="110" stroke="#5B1A3A"/><line x1="60" y1="135" x2="180" y2="135" stroke="#5B1A3A"/>
                <text x="120" y="45" text-anchor="middle" font-size="14" fill="#5B1A3A" font-weight="bold">Filtro: Ciudad = Tijuana</text>
            </svg>
        </div>
    </div>

    <!-- 4. DICE -->
    <div style="background: white; border: 1px solid #ddd; border-radius: 8px; padding: 20px; box-shadow: 0 4px 6px rgba(0,0,0,0.05);">
        <h3 style="color: #5B1A3A; margin-top: 0;">4. Dice (Cortar en dados)</h3>
        <p style="font-size: 14px; color: #666; margin-bottom: 5px;">Filtrar el cubo utilizando dos o más dimensiones simultáneamente.</p>
        <div style="background: #f8f9fa; border-left: 4px solid #5B1A3A; padding: 8px 12px; font-family: monospace; font-size: 14px; margin-bottom: 15px; color: #d63384;">
            En Pandas: df[(df['Ciudad'] == 'Tijuana') & (df['Año'] == 2026)]
        </div>
        <div style="display: flex; align-items: center; justify-content: space-around; flex-wrap: wrap;">
            
            <svg width="250" height="210" viewBox="0 0 250 210">
                <polygon points="60,60 180,60 225,30 105,30" fill="#FFF8E7" stroke="#5B1A3A" stroke-width="1.2"/>
                <polygon points="180,60 225,30 225,130 180,160" fill="#FFF8E7" stroke="#5B1A3A" stroke-width="1.2"/>
                <rect x="60" y="60" width="120" height="100" fill="#FFF8E7" stroke="#5B1A3A" stroke-width="1.2"/>
                <line x1="100" y1="60" x2="100" y2="160" stroke="#5B1A3A"/><line x1="140" y1="60" x2="140" y2="160" stroke="#5B1A3A"/>
                <line x1="60" y1="85" x2="180" y2="85" stroke="#5B1A3A"/><line x1="60" y1="110" x2="180" y2="110" stroke="#5B1A3A"/><line x1="60" y1="135" x2="180" y2="135" stroke="#5B1A3A"/>
                <line x1="100" y1="60" x2="145" y2="30" stroke="#5B1A3A"/><line x1="140" y1="60" x2="185" y2="30" stroke="#5B1A3A"/>
                <line x1="75" y1="50" x2="195" y2="50" stroke="#5B1A3A"/><line x1="90" y1="40" x2="210" y2="40" stroke="#5B1A3A"/>
                <line x1="180" y1="85" x2="225" y2="55" stroke="#5B1A3A"/><line x1="180" y1="110" x2="225" y2="80" stroke="#5B1A3A"/><line x1="180" y1="135" x2="225" y2="105" stroke="#5B1A3A"/>
                <line x1="195" y1="50" x2="195" y2="150" stroke="#5B1A3A"/><line x1="210" y1="40" x2="210" y2="140" stroke="#5B1A3A"/>
                
                <rect x="60" y="60" width="80" height="50" fill="#E6D3DC" stroke="#5B1A3A" stroke-width="2" opacity="0.8"/>
            </svg>

            <div style="text-align: center; color: #5B1A3A; font-weight: bold;">
                <span style="font-size: 24px;">&#10230;</span><br>Dice
            </div>

            <svg width="250" height="210" viewBox="0 0 250 210">
                <polygon points="80,100 160,100 190,80 110,80" fill="#E6D3DC" stroke="#5B1A3A" stroke-width="1.5"/>
                <polygon points="160,100 190,80 190,130 160,150" fill="#E6D3DC" stroke="#5B1A3A" stroke-width="1.5"/>
                <rect x="80" y="100" width="80" height="50" fill="#E6D3DC" stroke="#5B1A3A" stroke-width="1.5"/>
                <line x1="120" y1="100" x2="120" y2="150" stroke="#5B1A3A"/>
                <line x1="80" y1="125" x2="160" y2="125" stroke="#5B1A3A"/>
                <line x1="120" y1="100" x2="150" y2="80" stroke="#5B1A3A"/>
                <line x1="95" y1="90" x2="175" y2="90" stroke="#5B1A3A"/>
                <line x1="160" y1="125" x2="190" y2="105" stroke="#5B1A3A"/>
                <line x1="175" y1="90" x2="175" y2="140" stroke="#5B1A3A"/>
                <text x="135" y="170" text-anchor="middle" font-size="14" fill="#5B1A3A" font-weight="bold">Ciudad = Tijuana</text>
                <text x="135" y="185" text-anchor="middle" font-size="14" fill="#5B1A3A" font-weight="bold">& Año = 2026</text>
            </svg>
        </div>
    </div>
</div>
"""

display(HTML(cubos_olap))

# Laboratorio: Código Rojo en el Data Warehouse 🚨

Son los Ingenieros de Datos de "AutoMetrics". El script ETL falló. Su misión es arreglar la tubería de datos y luego ejecutar consultas OLAP para el equipo de negocios.

### Fase 1: OLTP (Extracción)
Simulamos la ingesta del sistema transaccional. Hay un error oculto en los salarios (`-999`).

In [6]:
import pandas as pd
import numpy as np

# EXTRACT
datos_crudos = pd.DataFrame({
    'id_empleado': [1, 2, 3, 4, 5],
    'nombre_ciudad': ['Ensenada', 'Tijuana', 'Ensenada', 'Mexicali', 'Tijuana'],
    'departamento': ['Ventas', 'IT', 'Ventas', 'IT', 'Ventas'],
    'salario_mensual': [25000, 30000, -999, 28000, 32000],
    'comentario_desempeno': ["Excelente", "Impuntual", "Buen trabajo", "Cumple", "Sobresaliente"]
})
datos_crudos.head()

,id_empleado,nombre_ciudad,departamento,salario_mensual,comentario_desempeno
0,1,Ensenada,Ventas,25000,Excelente
1,2,Tijuana,IT,30000,Impuntual
2,3,Ensenada,Ventas,-999,Buen trabajo
3,4,Mexicali,IT,28000,Cumple
4,5,Tijuana,Ventas,32000,Sobresaliente

In [9]:
# RETO 1: Limpia el valor corrupto de -999 antes de que contamine el almacén.
# TU CÓDIGO AQUÍ:
datos_crudos.loc[datos_crudos['salario_mensual'] < 0, 'salario_mensual'] = datos_crudos['salario_mensual'].median()
datos_crudos.head()

,id_empleado,nombre_ciudad,departamento,salario_mensual,comentario_desempeno
0,1,Ensenada,Ventas,25000,Excelente
1,2,Tijuana,IT,30000,Impuntual
2,3,Ensenada,Ventas,28000,Buen trabajo
3,4,Mexicali,IT,28000,Cumple
4,5,Tijuana,Ventas,32000,Sobresaliente

### Fase 2: ETL y Esquema Estrella (Transform & Load)
El ingeniero anterior provocó una Explosión Cartesiana al crear la dimensión y dejó una columna de texto gigante que destruirá la memoria RAM.

In [ ]:
# TRANSFORM
# RETO 2: Arregla la creación de la dimensión agregando el método para eliminar duplicados.
# dim_ciudad = datos_crudos[['nombre_ciudad']].copy() # <-- Arregla esta línea
dim_ciudad = datos_crudos[['nombre_ciudad']].drop_duplicates().reset_index(drop=True) # <-- Arregla esta línea
dim_ciudad['id_ciudad'] = dim_ciudad.index + 1

print(dim_ciudad.head())

dim_depto = datos_crudos[['departamento']].drop_duplicates().reset_index(drop=True)
dim_depto['id_depto'] = dim_depto.index + 1

print(dim_depto.head())

# Hacemos Merge para obtener los IDs
df_temp = datos_crudos.merge(dim_ciudad, on='nombre_ciudad', how='left')
df_temp = df_temp.merge(dim_depto, on='departamento', how='left')
df_temp.head()

  nombre_ciudad  id_ciudad
0      Ensenada          1
1       Tijuana          2
2      Mexicali          3
  departamento  id_depto
0       Ventas         1
1           IT         2

  nombre_ciudad  id_ciudad
0      Ensenada          1
1       Tijuana          2
2      Mexicali          3

In [18]:
# RETO 3: Construye la Tabla de Hechos aislando solo las llaves foráneas y el salario. 
# (Deja fuera el comentario de desempeño)
fact_rendimiento = df_temp[["id_ciudad", "id_depto", "salario_mensual"]] # <-- Arregla esta línea

# LOAD (La matriz KDD se consolida en memoria)
print("Data Warehouse Cargado.")
fact_rendimiento.head()

Data Warehouse Cargado.

   id_ciudad  id_depto  salario_mensual
0          1         1            25000
1          2         2            30000
2          1         1            28000
3          3         2            28000
4          2         1            32000

### Fase 3: Operaciones del Cubo OLAP
El almacén está listo. Ahora cruzamos hechos y dimensiones para responder preguntas de negocio usando operaciones OLAP.

In [22]:
# Reconstruimos el Cubo OLAP uniendo las tablas
cubo_olap = fact_rendimiento.merge(dim_ciudad, on='id_ciudad').merge(dim_depto, on='id_depto')
cubo_olap

   id_ciudad  id_depto  salario_mensual nombre_ciudad departamento
0          1         1            25000      Ensenada       Ventas
1          2         2            30000       Tijuana           IT
2          1         1            28000      Ensenada       Ventas
3          3         2            28000      Mexicali           IT
4          2         1            32000       Tijuana       Ventas

In [ ]:


# 1. ROLL-UP (Menos detalle): Salario total por Departamento
print("--- ROLL-UP ---")
print(cubo_olap.groupby('departamento')['salario_mensual'].sum())

--- ROLL-UP ---
departamento
IT        58000
Ventas    85000
Name: salario_mensual, dtype: int64

In [20]:
# 2. DRILL-DOWN (Más detalle): Salario total por Departamento y Ciudad
print("\n--- DRILL-DOWN ---")
print(cubo_olap.groupby(['departamento', 'nombre_ciudad'])['salario_mensual'].sum())

--- DRILL-DOWN ---
departamento  nombre_ciudad
IT            Mexicali         28000
              Tijuana          30000
Ventas        Ensenada         53000
              Tijuana          32000
Name: salario_mensual, dtype: int64

In [23]:
# RETO 4 (SLICE): Escribe una consulta que filtre el cubo SOLO para la ciudad de 'Tijuana'
slice_tijuana = cubo_olap[cubo_olap["nombre_ciudad"] == "Tijuana"]
print("\n--- SLICE ---")
print(slice_tijuana)

--- SLICE ---
   id_ciudad  id_depto  salario_mensual nombre_ciudad departamento
1          2         2            30000       Tijuana           IT
4          2         1            32000       Tijuana       Ventas

In [27]:
# RETO 5 (DICE): Escribe una consulta que filtre el cubo para 'Ventas' EN 'Ensenada'
dice_ventas_ens = cubo_olap[(cubo_olap["nombre_ciudad"] == "Ensenada") & (cubo_olap["departamento"] == "Ventas")]
print("\n--- DICE ---")
print(dice_ventas_ens)

--- DICE ---
   id_ciudad  id_depto  salario_mensual nombre_ciudad departamento
0          1         1            25000      Ensenada       Ventas
2          1         1            28000      Ensenada       Ventas